[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
